del getsectorx.m
del getsectory.m
del getroutebegin.m
del getrouteend.m
del getcircleinfo.m
del getcloudinfo.m
del showlinestinfo.m
del showcost.m
del showcostx.txt
del showcosty.txt
del *.pyc